<img src="<?php echo $this->baseUrl('/images/ewa.png');?>" name="Ewa Koziatek- psycholog" alt="Ewa Koziatek- psycholog" style="float: right; margin-right: 30px; margin-left: 30px;"/>
<p><strong>Ewa Koziatek</strong> - <strong>psycholog</strong>, absolwentka Katolickiego Uniwersytetu Lubelskiego, <strong>psychoterapeuta</strong> w trakcie procesu certyfikacji,  w trakcie podyplomowych studiów z <strong>zakresu psychoterapii</strong> w Katedrze Psychoterapii Collegium Medicum Uniwersytetu Jagiellońskiego w Krakowie pod kierunkiem prof. dr hab. n. med. Jerzego Aleksandrowicza. W trakcie specjalizacji z <strong>psychologii klinicznej</strong> w Wojewódzkim Zespole Lecznictwa Psychiatrycznego w Olsztynie.
<br/><br/>
Po studiach podstawowych wiedzę teoretyczną i <strong>doświadczenie</strong> w pracy pogłębiałam prowadząc zajęcia dydaktyczne w Katedrze Psychologii Społecznej Katolickiego Uniwersytetu Lubelskiego i pracując w Domu Pomocy Społecznej.
<br/><br/>
Po przeniesieniu się do Olsztyna  podjęłam pracę w Wojewódzkim Zespole Lecznictwa Psychiatrycznego, gdzie pracuję do dziś. Początkowo pracowałam w oddziale ogólnopsychiatrycznym a teraz jestem młodszym asysentem w oddziale dziennym. Do moich zadań należy pełna diagnostyka psychologiczna, wsparcie psychologiczne i psychoterapia. Od kilku lat pełnię funkcję biegłego sądowego przy Sądzie Okręgowym w Olsztynie.
Ciągle rozszerzam zakres swoich umiejętności psychologicznych poprzez  prowadzenie warsztatów i szkoleń z różnymi grupami zawodowymi.
<br/><br/>
Jestem członkiem Sekcji Naukowej Psychoterapii Polskiego Towarzystwa Psychiatrycznego i członkiem Polskiego Towarzystwa Psychologicznego.
<br/><br/>
Od kilku lat prowadzę gabinet prywatny. Specjalizuję się w pracy z osobami dorosłymi z <strong>zaburzeniami lękowymi, zaburzeniami afektywnymi (nastroju, m.in. depresja) i zaburzeniami osobowości</strong>. Prowadzę również diagnostykę psychologiczną.
<br/><br/>
W pracy terapeutycznej stosuję podejście integracyjne, choć dominującym paradygmatem jest podejście psychodynamiczne, dające możliwość spojrzenia w głąb siebie, nazawania obszarów trudnych, przeżycia doświadczenia korektywnego a przez to doprowadzenia do zmiany. Swoją pracę poddaję regularnej superwizji u akredytowanych superwizorów.
</p>