<p><br/>Prowadząc gabinet koncentruję się na pracy z osobami dorosłymi w zakresie:</p>
<h3>
<br/>- terapii indywidualnej osób z zaburzeniami lękowymi, zaburzeniami nastroju, zaburzeniami osobowości
<br/><br/>- poradnictwa psychologicznego w pokonywaniu kryzysów i trudności
<br/><br/>- diagnostyki psychologicznej
</h3>
<p><br/>Spotkania są umawiane na godziny popołudniowe. Organizacja pracy gabinetu zakłada, że każda osoba ma indywidualną godzinę i dzień wizyt. Harmonogram spotkań jest tak zaplanowany, by osoby wychodzące i wchodzące nie mogły się spotkać,
zapewniając anonimowość.</p>
