<h1>Witaj.</h1><br/>
<h2>Znajdujesz się na stronie prowadzonego przeze mnie gabinetu
psychologicznego.<br/>
<br/><br/>
Być może prowadziła Cię tu ciekawość, a może...<h2><br/><br/>
<h3>- napotkałeś trudności życiowe i zastanawiasz się nad podjęciem
współpracy z psychologiem, by poradzić sobie z kłopotami,
niepewnością<br/>
-  zdiagnozowano u Ciebie nerwice (zaburzenia lękowe), depresje,
zaburzenia osobowości i usłyszałeś sugestię by poddać się
psychoterapii lub sam o niej myślisz<br/>
- jesteś w sytuacji, gdzie Twój lekarz, robiąc dodatkowe badania,
mówi, że "nie widzi somatycznych przyczyn" Twojego bólu
fizycznego i proponuje spotkania z psychoterapeutą<br/>
- chorujesz na przewlekłą chorobę somatyczną i coraz trudniej jest
Ci sobie z nią radzić, bo widzisz więcej strat niż nowych
możliwości<br/>
- chcesz rozwoju swojej osobowości, bo w głębi siebie czujesz, że
możesz jeszcze nad sobą popracować by Twoje kontakty ze światem
były głębsze</h3><br/><br/><br/>
<h3>Jeżeli odnajdujesz się w którymś z tych opisów i jesteś osobą
dorosłą - zapraszam na konsultacje.<br/>
Spotkania są umawiane na godziny popołudniowe. Organizacja pracy gabinetu zakłada, że każda osoba ma indywidualną godzinę i dzień wizyt. Harmonogram spotkań jest tak zaplanowany, by osoby wychodzące i wchodzące nie mogły się spotkać, co zapewnia anonimowość.<br/><br/><br/></h3>
