<h4>
<iframe width="600" height="300" align="left" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.pl/maps?hl=pl&amp;ie=UTF8&amp;q=psycholog+olsztyn&amp;fb=1&amp;gl=pl&amp;hq=psycholog&amp;hnear=0x46e2792d071419c7:0x106a8126cf54c20f,Olsztyn&amp;cid=0,0,10298120545310112678&amp;t=h&amp;ll=53.779761,20.483859&amp;spn=0.003804,0.012853&amp;z=16&amp;iwloc=A&amp;output=embed"></iframe>
<br/>ul. Mickiewicza 4 p.319,<br/>
10-549 Olsztyn<br/>
<small><a href="https://maps.google.pl/maps?hl=pl&amp;ie=UTF8&amp;q=psycholog+olsztyn&amp;fb=1&amp;gl=pl&amp;hq=psycholog&amp;hnear=0x46e2792d071419c7:0x106a8126cf54c20f,Olsztyn&amp;cid=0,0,10298120545310112678&amp;t=h&amp;ll=53.779761,20.483859&amp;spn=0.003804,0.012853&amp;z=16&amp;iwloc=A&amp;source=embed">Wyświetl większą mapę</a></small>
<br/><br/><br/>
Rejestracja:<br/>
codziennie <br/>
nr tel. 604 988 722<br/>
mail: koziak1@o2.pl<br/><br/><br/></h4>
<p>Gabinet znajduje się na III piętrze, w budynku Spółdzielni Pracy Rolniczo- Handlowej w centrum Olsztyna (skrzyżowanie ulic Mickiewicza i Dąbrowszczaków).</p>
