<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl" lang="pl">
<head>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('css/style.css') ?>" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta name="robots" content="index,follow,all"/>
<meta name="keywords" content="psycholog, terapia, psychoterapia, psychoterapia, depresja, nerwica, poradnictwo psychologiczne, zaburzenia osobowości, psycholog olsztyn, tani psycholog olsztyn"/>
<meta name="description" content="Gabinet Psychologiczny Ewa Koziatek. Oferujemy najwyższą jakość usług i komfort spotkań. Terapia, psychoterapia, leczenie depresji, nerwicy, zaburzeń osobowości. Poradnictwo psychologiczne"/>
<title>Psycholog Ewa Koziatek. Poradnictwo Psychologiczne, Psychoterapia.</title>
<meta name="author" content="Leszek Koziatek"/>
</head>
    <body>
        <div id="head">
            <a href="<?php echo $this->url(array(), 'home') ?>"><img src="<?php echo $this->baseUrl('/images/head1.png'); ?>" title="gabinet psychologiczny Ewa Koziatek" alt="strona domowa gabinetu"/></a>
        </div>
        <div id="content">
            <div id="menu">
<a href="<?php echo $this->url(array(), 'gabinet') ?>"><img src="<?php echo $this->baseUrl('/images/gabinet1.png'); ?>" title="Gabinet Psychologiczny" alt="Gabinet Psychologiczny"/></a><a href="<?php echo $this->url(array(), 'about') ?>"><img src="<?php echo $this->baseUrl('/images/o mnie1.png'); ?>" title="O mnie" alt="O psychologu"/></a><a href="<?php echo $this->url(array(), 'kontakt') ?>"><img src="<?php echo $this->baseUrl('/images/kontakt1.png'); ?>" title="Kontakt z psychologiem" alt="Kontakt z psychologiem"/></a><a href="<?php echo $this->url(array(), 'kwalifikacje') ?>"><img src="<?php echo $this->baseUrl('/images/kwalifikacje1.png'); ?>" title="Kwalifikacje" alt="kwalifikacje"/></a><a href="<?php echo $this->url(array(), 'varia') ?>"><img src="<?php echo $this->baseUrl('/images/varia1.png'); ?>" title="Varia" alt="varia" /></a>
            </div>
            <div>
                <?php echo $this->layout()->content; ?>
                <br/>
            </div>
            <div id="footer">
Twórca Strony: Leszek Koziatek email:zlotylesk@o2.pl Wszelkie prawa zastrzeżone.
            </div></div>
</body>
</html>